name: insurance_app
description: Insurance App - A Flutter project for insurance services.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  http: ^1.4.0
  provider: ^6.0.5
  shared_preferences: ^2.5.3
  json_annotation: ^4.8.1
  flutter_secure_storage: ^8.0.0
  dio: ^5.8.0+1
  flutter_dotenv: ^5.2.1
  fluttertoast: ^8.2.2
  equatable: ^2.0.5
  uuid: ^4.5.1
  flutter_markdown: ^0.7.7+1
  just_audio: ^0.9.35
  file_picker: ^5.5.0
  path_provider: ^2.1.1
  intl: ^0.19.0
  timeago: ^3.7.1
  fl_chart: ^1.0.0
  table_calendar: ^3.0.9
  crypto: ^3.0.3
  archive: ^3.4.10
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/logo/
    - .env 